# this config was migrated from renv.lock on 2026-04-26
[project]
name = "/n/holylabs/cgolden_lab/Lab/projects/tinashe_land_use/LandUsePLN"
r_version = "4.5"

repositories = [
    { alias = "CRAN", url = "https://mirror.ibcp.fr/pub/CRAN"}
]

dependencies = [
    { name = "R6", repository = "CRAN" },
    { name = "RcppInt64", repository = "CRAN" },
    { name = "RcppTOML", repository = "CRAN" },
    { name = "askpass", repository = "CRAN" },
    { name = "backports", repository = "CRAN" },
    { name = "base64enc", repository = "CRAN" },
    { name = "base64url", repository = "CRAN" },
    { name = "bit", repository = "CRAN" },
    { name = "brew", repository = "CRAN" },
    { name = "brio", repository = "CRAN" },
    { name = "bslib", repository = "CRAN" },
    { name = "cachem", repository = "CRAN" },
    { name = "callr", repository = "CRAN" },
    { name = "cli", repository = "CRAN" },
    { name = "clipr", repository = "CRAN" },
    { name = "commonmark", repository = "CRAN" },
    { name = "config", repository = "CRAN" },
    { name = "crayon", repository = "CRAN" },
    { name = "credentials", repository = "CRAN" },
    { name = "curl", repository = "CRAN" },
    { name = "data.table", repository = "CRAN" },
    { name = "desc", repository = "CRAN" },
    { name = "devtools", repository = "CRAN" },
    { name = "diffobj", repository = "CRAN" },
    { name = "digest", repository = "CRAN" },
    { name = "downlit", repository = "CRAN" },
    { name = "dplyr", repository = "CRAN" },
    { name = "ellipsis", repository = "CRAN" },
    { name = "evaluate", repository = "CRAN" },
    { name = "fansi", repository = "CRAN" },
    { name = "fastmap", repository = "CRAN" },
    { name = "fledge", repository = "CRAN" },
    { name = "fontawesome", repository = "CRAN" },
    { name = "fs", repository = "CRAN" },
    { name = "fusen", repository = "CRAN" },
    { name = "gdalraster", repository = "CRAN" },
    { name = "generics", repository = "CRAN" },
    { name = "geodata", repository = "CRAN" },
    { name = "geotargets", repository = "CRAN" },
    { name = "gert", repository = "CRAN" },
    { name = "gh", repository = "CRAN" },
    { name = "gitcreds", repository = "CRAN" },
    { name = "glue", repository = "CRAN" },
    { name = "here", repository = "CRAN" },
    { name = "highr", repository = "CRAN" },
    { name = "hms", repository = "CRAN" },
    { name = "htmltools", repository = "CRAN" },
    { name = "htmlwidgets", repository = "CRAN" },
    { name = "httpuv", repository = "CRAN" },
    { name = "httr", repository = "CRAN" },
    { name = "httr2", repository = "CRAN" },
    { name = "ini", repository = "CRAN" },
    { name = "jquerylib", repository = "CRAN" },
    { name = "jsonlite", repository = "CRAN" },
    { name = "knitr", repository = "CRAN" },
    { name = "later", repository = "CRAN" },
    { name = "lifecycle", repository = "CRAN" },
    { name = "lightparser", repository = "CRAN" },
    { name = "magrittr", repository = "CRAN" },
    { name = "memoise", repository = "CRAN" },
    { name = "mime", repository = "CRAN" },
    { name = "miniUI", repository = "CRAN" },
    { name = "nanoarrow", repository = "CRAN" },
    { name = "openssl", repository = "CRAN" },
    { name = "otel", repository = "CRAN" },
    { name = "pak", repository = "CRAN" },
    { name = "pillar", repository = "CRAN" },
    { name = "pkgbuild", repository = "CRAN" },
    { name = "pkgconfig", repository = "CRAN" },
    { name = "pkgdown", repository = "CRAN" },
    { name = "pkgload", repository = "CRAN" },
    { name = "png", repository = "CRAN" },
    { name = "praise", repository = "CRAN" },
    { name = "prettyunits", repository = "CRAN" },
    { name = "profvis", repository = "CRAN" },
    { name = "progress", repository = "CRAN" },
    { name = "promises", repository = "CRAN" },
    { name = "ragg", repository = "CRAN" },
    { name = "rappdirs", repository = "CRAN" },
    { name = "rcmdcheck", repository = "CRAN" },
    { name = "readr", repository = "CRAN" },
    { name = "rematch2", repository = "CRAN" },
    { name = "remotes", repository = "CRAN" },
    { name = "reticulate", repository = "CRAN" },
    { name = "rlang", repository = "CRAN" },
    { name = "rmarkdown", repository = "CRAN" },
    { name = "roxygen2", repository = "CRAN" },
    { name = "rprojroot", repository = "CRAN" },
    { name = "rstudioapi", repository = "CRAN" },
    { name = "rversions", repository = "CRAN" },
    { name = "sass", repository = "CRAN" },
    { name = "secretbase", repository = "CRAN" },
    { name = "sessioninfo", repository = "CRAN" },
    { name = "shiny", repository = "CRAN" },
    { name = "sourcetools", repository = "CRAN" },
    { name = "stringi", repository = "CRAN" },
    { name = "stringr", repository = "CRAN" },
    { name = "sys", repository = "CRAN" },
    { name = "systemfonts", repository = "CRAN" },
    { name = "tarchetypes", git = "https://github.com/ropensci/tarchetypes", commit = "e1581f8e4bb4fbb643ca185aa54c4c8c641a24ef" },
    { name = "targets", repository = "CRAN" },
    { name = "terra", repository = "CRAN" },
    { name = "testthat", repository = "CRAN" },
    { name = "textshaping", repository = "CRAN" },
    { name = "tibble", repository = "CRAN" },
    { name = "tidyr", repository = "CRAN" },
    { name = "tidyselect", repository = "CRAN" },
    { name = "tinytex", repository = "CRAN" },
    { name = "tzdb", repository = "CRAN" },
    { name = "urlchecker", repository = "CRAN" },
    { name = "usethis", repository = "CRAN" },
    { name = "utf8", repository = "CRAN" },
    { name = "vroom", repository = "CRAN" },
    { name = "waldo", repository = "CRAN" },
    { name = "whisker", repository = "CRAN" },
    { name = "whoami", repository = "CRAN" },
    { name = "withr", repository = "CRAN" },
    { name = "wk", repository = "CRAN" },
    { name = "xfun", repository = "CRAN" },
    { name = "xml2", repository = "CRAN" },
    { name = "xopen", repository = "CRAN" },
    { name = "xtable", repository = "CRAN" },
    { name = "yaml", repository = "CRAN" },
    { name = "zip", repository = "CRAN" }
]
