# WARNING - Generated by {fusen} from dev/flat_download_landcover_geodata.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_bounding_box_for_iso_code works", {
  expect_true(inherits(get_bounding_box_for_iso_code, "function")) 
})

test_that("crop_landcover_with_box works", {
  expect_true(inherits(crop_landcover_with_box, "function")) 
})

test_that("download_landcover_geodata works", {
  expect_true(inherits(download_landcover_geodata, "function"))
})
