# WARNING - Generated by {fusen} from dev/flat_build_local_pipeline.Rmd: do not edit by hand # nolint: line_length_linter.

#' Build Targets Pipeline
#'
#' Dynamically build the targets pipeline for the project.
#' 
#' This function sets up the targets pipeline by defining a local `_targets.R` file
#' and using `tar_tangle()` to create the necessary targets from an Rmd file.
#' The Rmd file is, itself, this vignette — Pipeline Definition.
#' 
#' @importFrom here here
#' @importFrom fs file_copy file_exists
#' @importFrom cli cli_alert_success cli_alert_danger cli_alert_info cli_abort
#' @importFrom xfun gsub_file
#' @importFrom readr read_lines
#' @importFrom stringr str_subset
#' @return NULL
#' @export
#' @examples
#' #build_local_pipeline()
build_local_pipeline <- function(
  targets_notebook_name = "_target_notebook.Rmd", 
  targets_file_name = "_targets.R", 
  pkg_name = "LandUsePLN", 
  vignette_name = "pipeline-definition.Rmd",
  overwrite = FALSE
  ) {
  
  # Define the path to the targets notebook definition and file
  targets_notebook <- here(targets_notebook_name)
  targets_file <- here(targets_file_name)

  # fetch this installed vignette
  vignette_path <- system.file(paste0("extdata/", vignette_name), package = pkg_name)

  # assert that the vignette exists
  if (!file_exists(vignette_path)) {
    cli_alert_danger("Vignette '{vignette_name}' not found in package '{pkg_name}'.")
    cli_abort("Cannot proceed without the vignette file.")
  }

  # copy to local project
  file_copy(vignette_path, targets_notebook, overwrite = overwrite)
  # remove irrelevant quarto directives
  lines <- read_lines(targets_notebook) %>%
    str_subset("#\\| eval: no", negate = TRUE)
  writeLines(lines, targets_notebook)
  if(file_exists(targets_notebook)) {
    cli_alert_success("Created local targets notebook at: {targets_notebook}")
  } else {
    cli_abort("Failed to create targets notebook at: {targets_notebook}")
  }

  # fetch the installed template for _targets.R
  template_path <- system.file("_targets.R", package = pkg_name)

  # copy to local project
  file_copy(template_path, targets_file, overwrite = overwrite)
  cli_alert_success("Created local targets file at: {targets_file}")

  # replace the tar_tangle() default to use the local notebook name
  if(targets_notebook_name != "_target_notebook.Rmd") {
    
    gsub_file(
      targets_file,
      pattern = "_target_notebook.Rmd",
      replacement = targets_notebook_name
    )
    cli_alert_success("Updated targets file to use targets notebook: {targets_notebook_name}")
    
  }

  cli_alert_info("To build the base pipeline, run `targets::tar_make()` in your R console. Use `targets::tar_read()` or `targets::tar_load()` to access target outputs.")
  cli_alert_info("You can also edit the targets file to extend the pipeline as needed for your project.")

  return(invisible())
}
